/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    // By default, Docusaurus generates a sidebar from the docs folder structure
    //tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

    en: [
        'en/README',
        {
            type: 'category',
            label: 'Client',
            link: {
                type: "doc",
                id: "en/client/README"
            },
            items: [
                'en/client-setup/README',
            ],
        },
        {
            type: 'category',
            label: 'Accounts',
            link: {
                type: "doc",
                id: "en/accounts/README"
            },
            items: [
                'en/account-balance/README',
                'en/account-balance-token/README',
                'en/wallet-generate/README',
                'en/keystore/README',
                'en/hd-wallet/README',
                'en/address-check/README'
            ],
        },
        {
            type: 'category',
            label: 'Transactions',
            link: {
                type: "doc",
                id: "en/transactions/README"
            },
            items: [
                'en/block-query/README',
                'en/transaction-query/README',
                'en/transfer-eth/README',
                'en/transfer-tokens/README',
                'en/block-subscribe/README',
                'en/transaction-raw-create/README',
                'en/transaction-raw-send/README'
            ],
        },
        {
            type: 'category',
            label: 'Smart Contracts',
            link: {
                type: "doc",
                id: "en/smart-contracts/README"
            },
            items: [
                'en/smart-contract-compile/README',
                'en/smart-contract-deploy/README',
                'en/smart-contract-load/README',
                'en/smart-contract-read/README',
                'en/smart-contract-write/README',
                'en/smart-contract-bytecode/README',
                'en/smart-contract-read-erc20/README'
            ],
        },
        {
            type: 'category',
            label: 'Events',
            link: {
                type: "doc",
                id: "en/events/README"
            },
            items: [
                'en/event-subscribe/README',
                'en/event-read/README',
                'en/event-read-erc20/README',
                'en/event-read-0xprotocol/README'
            ],
        },
        {
            type: 'category',
            label: 'Signatures',
            link: {
                type: "doc",
                id: "en/signatures/README"
            },
            items: [
                'en/signature-generate/README',
                'en/signature-verify/README',
            ],
        },
        {
            type: 'category',
            label: 'Testing',
            link: {
                type: "doc",
                id: "en/test/README"
            },
            items: [
                'en/faucets/README',
                'en/client-simulated/README',
            ],
        },
        {
            type: 'category',
            label: 'Swarm',
            link: {
                type: "doc",
                id: "en/swarm/README"
            },
            items: [
                'en/swarm-setup/README',
                'en/swarm-upload/README',
                'en/swarm-download/README',
            ],
        },
        {
            type: 'category',
            label: 'Whisper',
            link: {
                type: "doc",
                id: "en/swarm/README"
            },
            items: [
                'en/whisper-client/README',
                'en/whisper-keys/README',
                'en/whisper-send/README',
                'en/whisper-subscribe/README',
            ],
        },
        {
            type: 'category',
            label: 'Utilities',
            link: {
                type: "doc",
                id: "en/util/README"
            },
            items: [
                'en/util-go/README',
            ],
        },
        'en/GLOSSARY',
        'en/resources/README',
    ],
    // But you can create a sidebar manually
    zh: [
        'zh/README',
        {
            type: 'category',
            label: '客户端',
            link: {
                type: "doc",
                id: "zh/client/README"
            },
            items: [
                'zh/client-setup/README',
            ],
        },
        {
            type: 'category',
            label: '以太坊账户',
            link: {
                type: "doc",
                id: "zh/accounts/README"
            },
            items: [
                'zh/account-balance/README',
                'zh/account-balance-token/README',
                'zh/wallet-generate/README',
                'zh/keystore/README',
                'zh/hd-wallet/README',
                'zh/address-check/README'
            ],
        },
        {
            type: 'category',
            label: '交易',
            link: {
                type: "doc",
                id: "zh/transactions/README"
            },
            items: [
                'zh/block-query/README',
                'zh/transaction-query/README',
                'zh/transfer-eth/README',
                'zh/transfer-tokens/README',
                'zh/block-subscribe/README',
                'zh/transaction-raw-create/README',
                'zh/transaction-raw-send/README'
            ],
        },
        {
            type: 'category',
            label: '智能合约',
            link: {
                type: "doc",
                id: "zh/smart-contracts/README"
            },
            items: [
                'zh/smart-contract-compile/README',
                'zh/smart-contract-deploy/README',
                'zh/smart-contract-load/README',
                'zh/smart-contract-read/README',
                'zh/smart-contract-write/README',
                'zh/smart-contract-bytecode/README',
                'zh/smart-contract-read-erc20/README'
            ],
        },
        {
            type: 'category',
            label: '事件日志',
            link: {
                type: "doc",
                id: "zh/events/README"
            },
            items: [
                'zh/event-subscribe/README',
                'zh/event-read/README',
                'zh/event-read-erc20/README',
                'zh/event-read-0xprotocol/README'
            ],
        },
        {
            type: 'category',
            label: '签名',
            link: {
                type: "doc",
                id: "zh/signatures/README"
            },
            items: [
                'zh/signature-generate/README',
                'zh/signature-verify/README',
            ],
        },
        {
            type: 'category',
            label: '测试',
            link: {
                type: "doc",
                id: "zh/test/README"
            },
            items: [
                'zh/faucets/README',
                'zh/client-simulated/README',
            ],
        },
        {
            type: 'category',
            label: 'Swarm存储',
            link: {
                type: "doc",
                id: "zh/swarm/README"
            },
            items: [
                'zh/swarm-setup/README',
                'zh/swarm-upload/README',
                'zh/swarm-download/README',
            ],
        },
        {
            type: 'category',
            label: 'Whisper通信协议',
            link: {
                type: "doc",
                id: "zh/swarm/README"
            },
            items: [
                'zh/whisper-client/README',
                'zh/whisper-keys/README',
                'zh/whisper-send/README',
                'zh/whisper-subscribe/README',
            ],
        },
        {
            type: 'category',
            label: '工具',
            link: {
                type: "doc",
                id: "zh/util/README"
            },
            items: [
                'zh/util-go/README',
            ],
        },
        'zh/GLOSSARY',
        'zh/resources/README',

    ]
};

module.exports = sidebars;
